sudo: false
language: rust
rust:
- 1.5.0
- stable
- beta
- nightly
script:
- (cd hello_world && cargo build --verbose)
- (cd syntex && cargo test --verbose && cargo doc --no-deps)
- (cd syntex_syntax && cargo doc --no-deps)
after_success: |
  [ $TRAVIS_BRANCH = "master" ] &&
  [ $TRAVIS_PULL_REQUEST  = false ] &&
  mkdir -p target/doc &&
  cp -r syntex/target/doc target/doc/syntex &&
  cp -r syntex_syntax/target/doc target/doc/syntex_syntax &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: MkGJwAWwduRZ7N8TjTtmftzlcIai0luUnpGwjGXOZ/xpKSVZddeQN/CRimVgua1a3tBvlQ15Fr4YNkwBeDU+G3ERIHCfTowzR0bhOo5NPBiULvp3l/u8ECp2IUa8kNh9XFH4DibFvmzhaiQa1eIdojLok24RP7E2XvBHPKw4xYI=
