[package]
name = "syntex"
version = "0.4.1"
authors = [ "erick.tryzelaar@gmail.com" ]
license = "MIT/Apache-2.0"
description = "High-level bindings to the zeromq library"
repository = "https://github.com/erickt/rust-zmq"

[dependencies]
syntex_syntax = "*"
