[package]
name = "hello_world"
version = "0.2.0"
authors = [ "erick.tryzelaar@gmail.com" ]
build = "build.rs"

[build-dependencies.syntex]
path = ".."

[build-dependencies.syntex_syntax]
path = "../syntex_syntax"

[build-dependencies.hello_world_macros]
path = "hello_world_macros"
