[package]
name = "hello_world"
version = "0.5.0"
authors = [ "erick.tryzelaar@gmail.com" ]
build = "build.rs"

[build-dependencies]
syntex = { version = "*", path = "../syntex" }

[build-dependencies.hello_world_macros]
path = "hello_world_macros"
