[package]
name = "syntex_fmt_macros"
version = "0.1.0"
authors = [ "erick.tryzelaar@gmail.com" ]
license = "MIT/Apache-2.0"
description = "Export of fmt_macros code generation"
repository = "https://github.com/erickt/rust-syntex"
