[package]
name = "hello_world_macros"
version = "0.4.3"
authors = [ "erick.tryzelaar@gmail.com" ]

[dependencies]
syntex = { version = "*", path = "../.." }
syntex_syntax = { version = "*", path = "../../syntex_syntax" }
