[package]
name = "syntex_errors"
version = "0.58.0"
authors = [ "erick.tryzelaar@gmail.com" ]
license = "MIT/Apache-2.0"
description = "Export of librustc_errors for code generation"
repository = "https://github.com/serde-rs/syntex"
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
libc = "0.2.13"
rustc-serialize = "0.3.16"
syntex_pos = { version = "0.58", path = "../syntex_pos" }
term = "0.4.4"
unicode-xid = "0.0.4"
